# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BalinaTestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BalinaTestProject
	pod 'HMSegmentedControl', '~> 1.5'
	pod 'SWRevealViewController', '~> 2.3'
	pod 'SkyFloatingLabelTextField', '~> 3.2'
	pod 'GoogleMaps', '~> 2.4'
	pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON', '4.0.0-alpha.1'
    pod 'IQKeyboardManagerSwift', '~> 4.0'


end
